[package]
name = "ppo"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.14", features = [
    "train",
    "wgpu",
    "ndarray",
    "fusion",
    "autodiff",
], git = "https://github.com/tracel-ai/burn" }
ndarray = "0.15"
rand = "0.8.5"
rand_distr = "0.4.3"
linfa-linalg = "0.1.0"
tracing = "0.1"
