[package]
name = "ppo"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15"
rand = "0.8.5"
rand_distr = "0.4.3"
linfa-linalg = "0.1.0"
tracing = "0.1"
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.6.1", features = [
    "cuda",
], rev = "ebf722b446cf516dcecbdaf3f18551e7dcc0e6fd" }
candle-nn = { git = "https://github.com/huggingface/candle.git", version = "0.6.1", features = [
    "cuda",
], rev = "ebf722b446cf516dcecbdaf3f18551e7dcc0e6fd" }

[dev-dependencies]
approx = "0.5"
